version: '3'
services:
  backend:
    image: modsaber-backend
    build: 'server'
    restart: always
    depends_on:
      - mongo
      - redis
    networks:
      - internal
      - proxy
    env_file:
      - site.env
    volumes:
      - cdn:/usr/app/src/store:rw
  proxy:
    image: nginx
    restart: always
    depends_on:
      - backend
    networks:
      - proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - cdn:/usr/share/nginx/cdn:ro
    ports:
      - '80:80'
  mongo:
    image: mongo:4
    restart: always
    networks:
      - internal
    volumes:
      - mongo:/data/db:rw
  redis:
    image: redis:alpine
    restart: 'always'
    networks:
      - internal
networks:
  proxy:
  internal:
volumes:
  cdn:
  mongo:
